
[enderman-changes]
	#whether Endermen can pick up and place down blocks.
	enderman_allowed_to_pick_up_and_place_blocks = false
	#the chance of Endermen spawning with a random block. 1 is 100% chance.
	#Range: 0.0 ~ 1.0
	block-spawning-chance = 0.2
	#the chance of Endermen spawning with a random block in the Nether. 1 is 100% chance.
	#Range: 0.0 ~ 1.0
	block-spawning-chance-nether = 0.05
	#the chance of Endermen spawning with a random block in the End. 1 is 100% chance.
	#Range: 0.0 ~ 1.0
	block-spawning-chance-end = 0.001
	#whether Shattered Endermen release Dragon Breath upon death.
	shattered_endermen_release_dragon_breath = true
	#whether Dragon Breath released by Shattered Endermen can be picked up with a bottle.
	shattered_endermen_dragon_breath_pickable = true
	#whether Endermen can spawn as Shattered Endermen.
	endermen_spawn_as_shattered = true
	#the additional chance Endermen have to teleport while fighting each tick. 1 is 100% chance.
	#Range: 0.0 ~ 1.0
	fight-teleport-chance = 0.003
	#the additional chance Shattered Endermen have to teleport while fighting each tick. 1 is 100% chance.
	#Range: 0.0 ~ 1.0
	shattered-fight-teleport-chance = 0.01

[creeper-changes]
	#whether Creeper explosions don't break blocks but make blocks fall.
	creper_explosion_replace = false
	#The radius creeper explosions can make blocks fall if `creper_explosion_replace` is enabled.
	#Range: 0 ~ 15
	creeper-fall-explosion-radius = 5
	#The radius creeper explosions deal damage in if `creper_explosion_replace` is enabled.
	#Range: 0 ~ 15
	creeper-explosion-radius = 6
	#The radius charged creeper explosions can make blocks fall if `creper_explosion_replace` is enabled
	#Range: 0 ~ 30
	charged-creeper-fall-explosion-radius = 8
	#The radius charged creeper explosions deal damage in if `creper_explosion_replace` is enabled
	#Range: 0 ~ 30
	charged-creeper-explosion-radius = 8
	#whether Creeper explosions cause the screen to shake.
	creper_explosion_screen_shake = true
	#whether Creeper sprint if their target is sprinting.
	can_creepers_sprint = true
	#whether Creeper sneak up quietly until discovered.
	do_creepers_sneak_up_on_target = true
	#whether Creeper explode when on fire.
	creepers_explode_when_on_fire = false
	#whether Charged Creepers are immune fire.
	charged_creepers_immune_to_fire = false
	#whether Creeper explosions knockback entities.
	creeper_explosion_knockback_entities = false
	#whether Creeper explosions set other Creepers off.
	creeper_explosion_chain_reaction = false
	#whether Creeper hiss before running from cats and ocelots.
	creeper_hiss_and_run_from_cats = true
	#whether Creeper go up to pigs and oink at them.
	creeper_oink_at_pigs = true
	#whether Creepers struck by lightning summon a new Charged Creeper miniboss. This also enables Beheading Spores, a new crop dropped by the Charged Creeper that allows you to renewably get heads.
	charged_creeper_miniboss = false

