#Equatorial distance is the distance between the spawn point and the equator, measured in blocks.The spawn point is located in the northern hemisphere, equidistant between the north pole and the equator.Since the Minecraft world is immense, the poles are defined as the zones with the lowest possible temperature to the north and south.Beyond those zones, the temperature remains consistently low until the world border.You will find the north pole 1 equatorial distance (eqd) north, the equator 1 eqd south, and the south pole 3 eqd south.Temperate zone is between 0 and 1/3 eqd north and 2 eqd south and 7/3 eqd southDeserts will spawn around 1/3 eqd south, and jungles at 2/3 eqd.In the north, cold biomes begin around 1/3 eqd north, and very cold biomes at 2/3 eqd.Some references: Earth-like: eqd= 10000000, Mars-like: eqd= 5000000, Moon-like: eqd= 2500000, Ceres-like: eqd=750000, Default: eqd= 50000, very small: eqd= 10000, The line: eqd= 100, Frostpunk: eqd=0
#Range: 0.0 ~ 6.0E12
equatorial_distance = 5000.0
#Set to true if you want the biomes' distribution pattern to loop until world border after the very cold regions
looping_world = true
#0: DEFAULT, 1: SIMPLIFIED, 2: LINEAR, 3: CUSTOM CIRCULAR, 4: CIRCULAR. You can see examples on the official modrinth page: https://modrinth.com/mod/natural-temperature/gallery
#Range: 0 ~ 4
generation_mode = 0
#Positive values will move the equator to the north, if you want the equator to be at 0 set this value the same as your equatorial_distance
#Range: -6.0E12 ~ 6.0E12
equator_offset = 0.0
#Set it to true to ignore the biome distribution pattern of the surface, useful for mods that generate underground biomes like terralith
randomize_underground = false
#Randomize the underground below this y
#Range: -6.0E12 ~ 6.0E12
randomize_underground_below_y = 45.0
# 0: random (total randomness, except under jungles), 1: half_random (some degree of similarity with biomes on the surface), 2: random_plus_jungle (total randomness, include under jungles)
#Range: 0 ~ 2
underground_randomization_type = 1
#True will use banded world generation also in the other dimensions
multidimensional_bands = false
#A percentage for heating or cooling the planet. Range (-100.0 , 100.0)
#Range: -100.0 ~ 100.0
global_temperature_modifier_percentage = 0.0
#A percentage to mitigate the planet climate (this reduce extreme climatic regions). Range (0.0 , 100.0)
#Range: 0.0 ~ 100.0
global_temperature_mitigation_percentage = 0.0
#This will add a wider transition band between the desert and the jungle in the default mode, this is useful if some modded biomes are not spawning
extra_bands = false
#This is a multiplier that will magnify the waving of the climatic bands, the proportion of the wave will stay the same, but it will change the scale of the wave
#Range: -6.0E12 ~ 6.0E12
wave_magnification = 2.0
#Range: -1.0 ~ 8.0
temperature_zone_1 = 0.0
#Range: -1.0 ~ 8.0
temperature_zone_2 = 8.0
#Range: -1.0 ~ 8.0
temperature_zone_3 = 1.0
#(Range -1.0 , 1.0 ) These parameters are used to customize some of the modes, 1.0 are very hot zones, -1.0 are very cold zone. 8.0 will randomize the zone
#Range: -1.0 ~ 8.0
temperature_zone_4 = -1.0

